INSERT INTO APPLIES VALUES
(
    (SELECT T.ticket_num FROM TICKET AS T WHERE T.ticket_num = 46),
    (SELECT D.discount_code FROM DISCOUNT AS D WHERE D.type = 'STUDENT')
);

INSERT INTO APPLIES VALUES
(
    (SELECT T.ticket_num FROM TICKET AS T WHERE T.ticket_num = 47),
    (SELECT D.discount_code FROM DISCOUNT AS D WHERE D.type = 'STUDENT')
);

INSERT INTO APPLIES VALUES
(
    (SELECT T.ticket_num FROM TICKET AS T WHERE T.ticket_num = 48),
    (SELECT D.discount_code FROM DISCOUNT AS D WHERE D.type = 'STUDENT')
);

INSERT INTO APPLIES VALUES
(
    (SELECT T.ticket_num FROM TICKET AS T WHERE T.ticket_num = 49),
    (SELECT D.discount_code FROM DISCOUNT AS D WHERE D.type = 'STUDENT')
);

INSERT INTO APPLIES VALUES
(
    (SELECT T.ticket_num FROM TICKET AS T WHERE T.ticket_num = 50),
    (SELECT D.discount_code FROM DISCOUNT AS D WHERE D.type = 'STUDENT')
);

INSERT INTO APPLIES VALUES
(
    (SELECT T.ticket_num FROM TICKET AS T WHERE T.ticket_num = 51),
    (SELECT D.discount_code FROM DISCOUNT AS D WHERE D.type = 'STUDENT')
);

INSERT INTO APPLIES VALUES
(
    (SELECT T.ticket_num FROM TICKET AS T WHERE T.ticket_num = 52),
    (SELECT D.discount_code FROM DISCOUNT AS D WHERE D.type = 'STUDENT')
);

INSERT INTO APPLIES VALUES
(
    (SELECT T.ticket_num FROM TICKET AS T WHERE T.ticket_num = 53),
    (SELECT D.discount_code FROM DISCOUNT AS D WHERE D.type = 'STUDENT')
);

INSERT INTO APPLIES VALUES
(
    (SELECT T.ticket_num FROM TICKET AS T WHERE T.ticket_num = 54),
    (SELECT D.discount_code FROM DISCOUNT AS D WHERE D.type = 'STUDENT')
);

INSERT INTO APPLIES VALUES
(
    (SELECT T.ticket_num FROM TICKET AS T WHERE T.ticket_num = 55),
    (SELECT D.discount_code FROM DISCOUNT AS D WHERE D.type = 'STUDENT')
);

INSERT INTO APPLIES VALUES
(
    (SELECT T.ticket_num FROM TICKET AS T WHERE T.ticket_num = 121),
    (SELECT D.discount_code FROM DISCOUNT AS D WHERE D.type = 'STUDENT')
);

INSERT INTO APPLIES VALUES
(
    (SELECT T.ticket_num FROM TICKET AS T WHERE T.ticket_num = 122),
    (SELECT D.discount_code FROM DISCOUNT AS D WHERE D.type = 'STUDENT')
);

INSERT INTO APPLIES VALUES
(
    (SELECT T.ticket_num FROM TICKET AS T WHERE T.ticket_num = 123),
    (SELECT D.discount_code FROM DISCOUNT AS D WHERE D.type = 'STUDENT')
);

INSERT INTO APPLIES VALUES
(
    (SELECT T.ticket_num FROM TICKET AS T WHERE T.ticket_num = 124),
    (SELECT D.discount_code FROM DISCOUNT AS D WHERE D.type = 'STUDENT')
);

INSERT INTO APPLIES VALUES
(
    (SELECT T.ticket_num FROM TICKET AS T WHERE T.ticket_num = 125),
    (SELECT D.discount_code FROM DISCOUNT AS D WHERE D.type = 'STUDENT')
);

INSERT INTO APPLIES VALUES
(
    (SELECT T.ticket_num FROM TICKET AS T WHERE T.ticket_num = 126),
    (SELECT D.discount_code FROM DISCOUNT AS D WHERE D.type = 'STUDENT')
);

INSERT INTO APPLIES VALUES
(
    (SELECT T.ticket_num FROM TICKET AS T WHERE T.ticket_num = 127),
    (SELECT D.discount_code FROM DISCOUNT AS D WHERE D.type = 'STUDENT')
);

INSERT INTO APPLIES VALUES
(
    (SELECT T.ticket_num FROM TICKET AS T WHERE T.ticket_num = 128),
    (SELECT D.discount_code FROM DISCOUNT AS D WHERE D.type = 'STUDENT')
);

INSERT INTO APPLIES VALUES
(
    (SELECT T.ticket_num FROM TICKET AS T WHERE T.ticket_num = 129),
    (SELECT D.discount_code FROM DISCOUNT AS D WHERE D.type = 'STUDENT')
);

INSERT INTO APPLIES VALUES
(
    (SELECT T.ticket_num FROM TICKET AS T WHERE T.ticket_num = 130),
    (SELECT D.discount_code FROM DISCOUNT AS D WHERE D.type = 'STUDENT')
);

INSERT INTO APPLIES VALUES
(
    (SELECT T.ticket_num FROM TICKET AS T WHERE T.ticket_num = 56),
    (SELECT D.discount_code FROM DISCOUNT AS D WHERE D.type = 'UNEMPLOYED')
);

INSERT INTO APPLIES VALUES
(
    (SELECT T.ticket_num FROM TICKET AS T WHERE T.ticket_num = 57),
    (SELECT D.discount_code FROM DISCOUNT AS D WHERE D.type = 'UNEMPLOYED')
);

INSERT INTO APPLIES VALUES
(
    (SELECT T.ticket_num FROM TICKET AS T WHERE T.ticket_num = 58),
    (SELECT D.discount_code FROM DISCOUNT AS D WHERE D.type = 'UNEMPLOYED')
);

INSERT INTO APPLIES VALUES
(
    (SELECT T.ticket_num FROM TICKET AS T WHERE T.ticket_num = 131),
    (SELECT D.discount_code FROM DISCOUNT AS D WHERE D.type = 'UNEMPLOYED')
);

INSERT INTO APPLIES VALUES
(
    (SELECT T.ticket_num FROM TICKET AS T WHERE T.ticket_num = 132),
    (SELECT D.discount_code FROM DISCOUNT AS D WHERE D.type = 'UNEMPLOYED')
);

INSERT INTO APPLIES VALUES
(
    (SELECT T.ticket_num FROM TICKET AS T WHERE T.ticket_num = 59),
    (SELECT D.discount_code FROM DISCOUNT AS D WHERE D.type = 'LARGE FAMILIES')
);

INSERT INTO APPLIES VALUES
(
    (SELECT T.ticket_num FROM TICKET AS T WHERE T.ticket_num = 60),
    (SELECT D.discount_code FROM DISCOUNT AS D WHERE D.type = 'LARGE FAMILIES')
);

INSERT INTO APPLIES VALUES
(
    (SELECT T.ticket_num FROM TICKET AS T WHERE T.ticket_num = 133),
    (SELECT D.discount_code FROM DISCOUNT AS D WHERE D.type = 'LARGE FAMILIES')
);

INSERT INTO APPLIES VALUES
(
    (SELECT T.ticket_num FROM TICKET AS T WHERE T.ticket_num = 134),
    (SELECT D.discount_code FROM DISCOUNT AS D WHERE D.type = 'LARGE FAMILIES')
);

INSERT INTO APPLIES VALUES
(
    (SELECT T.ticket_num FROM TICKET AS T WHERE T.ticket_num = 135),
    (SELECT D.discount_code FROM DISCOUNT AS D WHERE D.type = 'LARGE FAMILIES')
);

INSERT INTO APPLIES VALUES
(
    (SELECT T.ticket_num FROM TICKET AS T WHERE T.ticket_num = 61),
    (SELECT D.discount_code FROM DISCOUNT AS D WHERE D.type = 'UNDERAGED')
);

INSERT INTO APPLIES VALUES
(
    (SELECT T.ticket_num FROM TICKET AS T WHERE T.ticket_num = 62),
    (SELECT D.discount_code FROM DISCOUNT AS D WHERE D.type = 'UNDERAGED')
);

INSERT INTO APPLIES VALUES
(
    (SELECT T.ticket_num FROM TICKET AS T WHERE T.ticket_num = 63),
    (SELECT D.discount_code FROM DISCOUNT AS D WHERE D.type = 'UNDERAGED')
);

INSERT INTO APPLIES VALUES
(
    (SELECT T.ticket_num FROM TICKET AS T WHERE T.ticket_num = 64),
    (SELECT D.discount_code FROM DISCOUNT AS D WHERE D.type = 'UNDERAGED')
);

INSERT INTO APPLIES VALUES
(
    (SELECT T.ticket_num FROM TICKET AS T WHERE T.ticket_num = 65),
    (SELECT D.discount_code FROM DISCOUNT AS D WHERE D.type = 'UNDERAGED')
);

INSERT INTO APPLIES VALUES
(
    (SELECT T.ticket_num FROM TICKET AS T WHERE T.ticket_num = 66),
    (SELECT D.discount_code FROM DISCOUNT AS D WHERE D.type = 'UNDERAGED')
);

INSERT INTO APPLIES VALUES
(
    (SELECT T.ticket_num FROM TICKET AS T WHERE T.ticket_num = 67),
    (SELECT D.discount_code FROM DISCOUNT AS D WHERE D.type = 'UNDERAGED')
);

INSERT INTO APPLIES VALUES
(
    (SELECT T.ticket_num FROM TICKET AS T WHERE T.ticket_num = 68),
    (SELECT D.discount_code FROM DISCOUNT AS D WHERE D.type = 'UNDERAGED')
);

INSERT INTO APPLIES VALUES
(
    (SELECT T.ticket_num FROM TICKET AS T WHERE T.ticket_num = 69),
    (SELECT D.discount_code FROM DISCOUNT AS D WHERE D.type = 'UNDERAGED')
);

INSERT INTO APPLIES VALUES
(
    (SELECT T.ticket_num FROM TICKET AS T WHERE T.ticket_num = 70),
    (SELECT D.discount_code FROM DISCOUNT AS D WHERE D.type = 'UNDERAGED')
);

INSERT INTO APPLIES VALUES
(
    (SELECT T.ticket_num FROM TICKET AS T WHERE T.ticket_num = 136),
    (SELECT D.discount_code FROM DISCOUNT AS D WHERE D.type = 'UNDERAGED')
);

INSERT INTO APPLIES VALUES
(
    (SELECT T.ticket_num FROM TICKET AS T WHERE T.ticket_num = 137),
    (SELECT D.discount_code FROM DISCOUNT AS D WHERE D.type = 'UNDERAGED')
);

INSERT INTO APPLIES VALUES
(
    (SELECT T.ticket_num FROM TICKET AS T WHERE T.ticket_num = 138),
    (SELECT D.discount_code FROM DISCOUNT AS D WHERE D.type = 'UNDERAGED')
);

INSERT INTO APPLIES VALUES
(
    (SELECT T.ticket_num FROM TICKET AS T WHERE T.ticket_num = 139),
    (SELECT D.discount_code FROM DISCOUNT AS D WHERE D.type = 'UNDERAGED')
);

INSERT INTO APPLIES VALUES
(
    (SELECT T.ticket_num FROM TICKET AS T WHERE T.ticket_num = 140),
    (SELECT D.discount_code FROM DISCOUNT AS D WHERE D.type = 'UNDERAGED')
);

INSERT INTO APPLIES VALUES
(
    (SELECT T.ticket_num FROM TICKET AS T WHERE T.ticket_num = 141),
    (SELECT D.discount_code FROM DISCOUNT AS D WHERE D.type = 'UNDERAGED')
);

INSERT INTO APPLIES VALUES
(
    (SELECT T.ticket_num FROM TICKET AS T WHERE T.ticket_num = 142),
    (SELECT D.discount_code FROM DISCOUNT AS D WHERE D.type = 'UNDERAGED')
);

INSERT INTO APPLIES VALUES
(
    (SELECT T.ticket_num FROM TICKET AS T WHERE T.ticket_num = 143),
    (SELECT D.discount_code FROM DISCOUNT AS D WHERE D.type = 'UNDERAGED')
);

INSERT INTO APPLIES VALUES
(
    (SELECT T.ticket_num FROM TICKET AS T WHERE T.ticket_num = 144),
    (SELECT D.discount_code FROM DISCOUNT AS D WHERE D.type = 'UNDERAGED')
);

INSERT INTO APPLIES VALUES
(
    (SELECT T.ticket_num FROM TICKET AS T WHERE T.ticket_num = 145),
    (SELECT D.discount_code FROM DISCOUNT AS D WHERE D.type = 'UNDERAGED')
);

INSERT INTO APPLIES VALUES
(
    (SELECT T.ticket_num FROM TICKET AS T WHERE T.ticket_num = 71),
    (SELECT D.discount_code FROM DISCOUNT AS D WHERE D.type = 'DISABLED')
);

INSERT INTO APPLIES VALUES
(
    (SELECT T.ticket_num FROM TICKET AS T WHERE T.ticket_num = 72),
    (SELECT D.discount_code FROM DISCOUNT AS D WHERE D.type = 'DISABLED')
);

INSERT INTO APPLIES VALUES
(
    (SELECT T.ticket_num FROM TICKET AS T WHERE T.ticket_num = 73),
    (SELECT D.discount_code FROM DISCOUNT AS D WHERE D.type = 'DISABLED')
);

INSERT INTO APPLIES VALUES
(
    (SELECT T.ticket_num FROM TICKET AS T WHERE T.ticket_num = 74),
    (SELECT D.discount_code FROM DISCOUNT AS D WHERE D.type = 'DISABLED')
);

INSERT INTO APPLIES VALUES
(
    (SELECT T.ticket_num FROM TICKET AS T WHERE T.ticket_num = 75),
    (SELECT D.discount_code FROM DISCOUNT AS D WHERE D.type = 'DISABLED')
);

INSERT INTO APPLIES VALUES
(
    (SELECT T.ticket_num FROM TICKET AS T WHERE T.ticket_num = 146),
    (SELECT D.discount_code FROM DISCOUNT AS D WHERE D.type = 'DISABLED')
);

INSERT INTO APPLIES VALUES
(
    (SELECT T.ticket_num FROM TICKET AS T WHERE T.ticket_num = 147),
    (SELECT D.discount_code FROM DISCOUNT AS D WHERE D.type = 'DISABLED')
);

INSERT INTO APPLIES VALUES
(
    (SELECT T.ticket_num FROM TICKET AS T WHERE T.ticket_num = 148),
    (SELECT D.discount_code FROM DISCOUNT AS D WHERE D.type = 'DISABLED')
);

INSERT INTO APPLIES VALUES
(
    (SELECT T.ticket_num FROM TICKET AS T WHERE T.ticket_num = 149),
    (SELECT D.discount_code FROM DISCOUNT AS D WHERE D.type = 'DISABLED')
);

INSERT INTO APPLIES VALUES
(
    (SELECT T.ticket_num FROM TICKET AS T WHERE T.ticket_num = 150),
    (SELECT D.discount_code FROM DISCOUNT AS D WHERE D.type = 'DISABLED')
);