INSERT INTO VISITS VALUES
(
    (SELECT V.id FROM VISITOR AS V WHERE V.id == 1),
    (SELECT Ex.id FROM EXHIBITION AS Ex WHERE Ex.id == 1),
    '2020-05-23'
);

INSERT INTO VISITS VALUES
(
    (SELECT V.id FROM VISITOR AS V WHERE V.id == 2),
    (SELECT Ex.id FROM EXHIBITION AS Ex WHERE Ex.id == 1),
    '2020-05-23'
);

INSERT INTO VISITS VALUES
(
    (SELECT V.id FROM VISITOR AS V WHERE V.id == 3),
    (SELECT Ex.id FROM EXHIBITION AS Ex WHERE Ex.id == 1),
    '2020-05-23'
);

INSERT INTO VISITS VALUES
(
    (SELECT V.id FROM VISITOR AS V WHERE V.id == 4),
    (SELECT Ex.id FROM EXHIBITION AS Ex WHERE Ex.id == 1),
    '2020-05-23'
);

INSERT INTO VISITS VALUES
(
    (SELECT V.id FROM VISITOR AS V WHERE V.id == 5),
    (SELECT Ex.id FROM EXHIBITION AS Ex WHERE Ex.id == 1),
    '2020-05-23'
);

INSERT INTO VISITS VALUES
(
    (SELECT V.id FROM VISITOR AS V WHERE V.id == 6),
    (SELECT Ex.id FROM EXHIBITION AS Ex WHERE Ex.id == 1),
    '2020-05-23'
);

INSERT INTO VISITS VALUES
(
    (SELECT V.id FROM VISITOR AS V WHERE V.id == 7),
    (SELECT Ex.id FROM EXHIBITION AS Ex WHERE Ex.id == 1),
    '2020-05-23'
);

INSERT INTO VISITS VALUES
(
    (SELECT V.id FROM VISITOR AS V WHERE V.id == 8),
    (SELECT Ex.id FROM EXHIBITION AS Ex WHERE Ex.id == 1),
    '2020-05-23'
);

INSERT INTO VISITS VALUES
(
    (SELECT V.id FROM VISITOR AS V WHERE V.id == 9),
    (SELECT Ex.id FROM EXHIBITION AS Ex WHERE Ex.id == 1),
    '2020-05-23'
);

INSERT INTO VISITS VALUES
(
    (SELECT V.id FROM VISITOR AS V WHERE V.id == 10),
    (SELECT Ex.id FROM EXHIBITION AS Ex WHERE Ex.id == 1),
    '2020-05-23'
);

INSERT INTO VISITS VALUES
(
    (SELECT V.id FROM VISITOR AS V WHERE V.id == 11),
    (SELECT Ex.id FROM EXHIBITION AS Ex WHERE Ex.id == 1),
    '2020-05-24'
);

INSERT INTO VISITS VALUES
(
    (SELECT V.id FROM VISITOR AS V WHERE V.id == 12),
    (SELECT Ex.id FROM EXHIBITION AS Ex WHERE Ex.id == 1),
    '2020-05-24'
);

INSERT INTO VISITS VALUES
(
    (SELECT V.id FROM VISITOR AS V WHERE V.id == 13),
    (SELECT Ex.id FROM EXHIBITION AS Ex WHERE Ex.id == 1),
    '2020-05-24'
);

INSERT INTO VISITS VALUES
(
    (SELECT V.id FROM VISITOR AS V WHERE V.id == 14),
    (SELECT Ex.id FROM EXHIBITION AS Ex WHERE Ex.id == 1),
    '2020-05-24'
);

INSERT INTO VISITS VALUES
(
    (SELECT V.id FROM VISITOR AS V WHERE V.id == 60),
    (SELECT Ex.id FROM EXHIBITION AS Ex WHERE Ex.id == 1),
    '2020-05-24'
);

INSERT INTO VISITS VALUES
(
    (SELECT V.id FROM VISITOR AS V WHERE V.id == 61),
    (SELECT Ex.id FROM EXHIBITION AS Ex WHERE Ex.id == 1),
    '2020-05-24'
);

INSERT INTO VISITS VALUES
(
    (SELECT V.id FROM VISITOR AS V WHERE V.id == 62),
    (SELECT Ex.id FROM EXHIBITION AS Ex WHERE Ex.id == 1),
    '2020-05-24'
);

INSERT INTO VISITS VALUES
(
    (SELECT V.id FROM VISITOR AS V WHERE V.id == 15),
    (SELECT Ex.id FROM EXHIBITION AS Ex WHERE Ex.id == 1),
    '2020-05-30'
);

INSERT INTO VISITS VALUES
(
    (SELECT V.id FROM VISITOR AS V WHERE V.id == 16),
    (SELECT Ex.id FROM EXHIBITION AS Ex WHERE Ex.id == 1),
    '2020-05-30'
);

INSERT INTO VISITS VALUES
(
    (SELECT V.id FROM VISITOR AS V WHERE V.id == 17),
    (SELECT Ex.id FROM EXHIBITION AS Ex WHERE Ex.id == 1),
    '2020-05-30'
);

INSERT INTO VISITS VALUES
(
    (SELECT V.id FROM VISITOR AS V WHERE V.id == 18),
    (SELECT Ex.id FROM EXHIBITION AS Ex WHERE Ex.id == 1),
    '2020-05-30'
);

INSERT INTO VISITS VALUES
(
    (SELECT V.id FROM VISITOR AS V WHERE V.id == 19),
    (SELECT Ex.id FROM EXHIBITION AS Ex WHERE Ex.id == 1),
    '2020-05-30'
);

INSERT INTO VISITS VALUES
(
    (SELECT V.id FROM VISITOR AS V WHERE V.id == 20),
    (SELECT Ex.id FROM EXHIBITION AS Ex WHERE Ex.id == 1),
    '2020-05-30'
);

INSERT INTO VISITS VALUES
(
    (SELECT V.id FROM VISITOR AS V WHERE V.id == 21),
    (SELECT Ex.id FROM EXHIBITION AS Ex WHERE Ex.id == 1),
    '2020-05-30'
);

INSERT INTO VISITS VALUES
(
    (SELECT V.id FROM VISITOR AS V WHERE V.id == 22),
    (SELECT Ex.id FROM EXHIBITION AS Ex WHERE Ex.id == 1),
    '2020-05-31'
);

INSERT INTO VISITS VALUES
(
    (SELECT V.id FROM VISITOR AS V WHERE V.id == 23),
    (SELECT Ex.id FROM EXHIBITION AS Ex WHERE Ex.id == 1),
    '2020-05-31'
);

INSERT INTO VISITS VALUES
(
    (SELECT V.id FROM VISITOR AS V WHERE V.id == 24),
    (SELECT Ex.id FROM EXHIBITION AS Ex WHERE Ex.id == 1),
    '2020-05-31'
);

INSERT INTO VISITS VALUES
(
    (SELECT V.id FROM VISITOR AS V WHERE V.id == 25),
    (SELECT Ex.id FROM EXHIBITION AS Ex WHERE Ex.id == 1),
    '2020-05-31'
);

INSERT INTO VISITS VALUES
(
    (SELECT V.id FROM VISITOR AS V WHERE V.id == 80),
    (SELECT Ex.id FROM EXHIBITION AS Ex WHERE Ex.id == 1),
    '2020-05-31'
);

INSERT INTO VISITS VALUES
(
    (SELECT V.id FROM VISITOR AS V WHERE V.id == 81),
    (SELECT Ex.id FROM EXHIBITION AS Ex WHERE Ex.id == 1),
    '2020-05-31'
);

INSERT INTO VISITS VALUES
(
    (SELECT V.id FROM VISITOR AS V WHERE V.id == 82),
    (SELECT Ex.id FROM EXHIBITION AS Ex WHERE Ex.id == 1),
    '2020-05-31'
);

INSERT INTO VISITS VALUES
(
    (SELECT V.id FROM VISITOR AS V WHERE V.id == 83),
    (SELECT Ex.id FROM EXHIBITION AS Ex WHERE Ex.id == 1),
    '2020-05-31'
);

INSERT INTO VISITS VALUES
(
    (SELECT V.id FROM VISITOR AS V WHERE V.id == 84),
    (SELECT Ex.id FROM EXHIBITION AS Ex WHERE Ex.id == 1),
    '2020-05-31'
);

INSERT INTO VISITS VALUES
(
    (SELECT V.id FROM VISITOR AS V WHERE V.id == 90),
    (SELECT Ex.id FROM EXHIBITION AS Ex WHERE Ex.id == 1),
    '2020-05-31'
);

INSERT INTO VISITS VALUES
(
    (SELECT V.id FROM VISITOR AS V WHERE V.id == 91),
    (SELECT Ex.id FROM EXHIBITION AS Ex WHERE Ex.id == 1),
    '2020-05-31'
);

INSERT INTO VISITS VALUES
(
    (SELECT V.id FROM VISITOR AS V WHERE V.id == 92),
    (SELECT Ex.id FROM EXHIBITION AS Ex WHERE Ex.id == 1),
    '2020-05-31'
);

INSERT INTO VISITS VALUES
(
    (SELECT V.id FROM VISITOR AS V WHERE V.id == 93),
    (SELECT Ex.id FROM EXHIBITION AS Ex WHERE Ex.id == 1),
    '2020-05-31'
);

INSERT INTO VISITS VALUES
(
    (SELECT V.id FROM VISITOR AS V WHERE V.id == 94),
    (SELECT Ex.id FROM EXHIBITION AS Ex WHERE Ex.id == 1),
    '2020-05-31'
);

INSERT INTO VISITS VALUES
(
    (SELECT V.id FROM VISITOR AS V WHERE V.id == 95),
    (SELECT Ex.id FROM EXHIBITION AS Ex WHERE Ex.id == 1),
    '2020-05-31'
);

INSERT INTO VISITS VALUES
(
    (SELECT V.id FROM VISITOR AS V WHERE V.id == 96),
    (SELECT Ex.id FROM EXHIBITION AS Ex WHERE Ex.id == 1),
    '2020-05-31'
);

INSERT INTO VISITS VALUES
(
    (SELECT V.id FROM VISITOR AS V WHERE V.id == 26),
    (SELECT Ex.id FROM EXHIBITION AS Ex WHERE Ex.id == 1),
    '2020-08-12'
);

INSERT INTO VISITS VALUES
(
    (SELECT V.id FROM VISITOR AS V WHERE V.id == 27),
    (SELECT Ex.id FROM EXHIBITION AS Ex WHERE Ex.id == 1),
    '2020-08-12'
);

INSERT INTO VISITS VALUES
(
    (SELECT V.id FROM VISITOR AS V WHERE V.id == 28),
    (SELECT Ex.id FROM EXHIBITION AS Ex WHERE Ex.id == 1),
    '2020-08-12'
);

INSERT INTO VISITS VALUES
(
    (SELECT V.id FROM VISITOR AS V WHERE V.id == 29),
    (SELECT Ex.id FROM EXHIBITION AS Ex WHERE Ex.id == 1),
    '2020-08-12'
);

INSERT INTO VISITS VALUES
(
    (SELECT V.id FROM VISITOR AS V WHERE V.id == 30),
    (SELECT Ex.id FROM EXHIBITION AS Ex WHERE Ex.id == 1),
    '2020-08-12'
);

INSERT INTO VISITS VALUES
(
    (SELECT V.id FROM VISITOR AS V WHERE V.id == 40),
    (SELECT Ex.id FROM EXHIBITION AS Ex WHERE Ex.id == 1),
    '2020-08-12'
);

INSERT INTO VISITS VALUES
(
    (SELECT V.id FROM VISITOR AS V WHERE V.id == 41),
    (SELECT Ex.id FROM EXHIBITION AS Ex WHERE Ex.id == 1),
    '2020-08-12'
);

INSERT INTO VISITS VALUES
(
    (SELECT V.id FROM VISITOR AS V WHERE V.id == 42),
    (SELECT Ex.id FROM EXHIBITION AS Ex WHERE Ex.id == 1),
    '2020-08-12'
);

INSERT INTO VISITS VALUES
(
    (SELECT V.id FROM VISITOR AS V WHERE V.id == 43),
    (SELECT Ex.id FROM EXHIBITION AS Ex WHERE Ex.id == 1),
    '2020-08-12'
);

INSERT INTO VISITS VALUES
(
    (SELECT V.id FROM VISITOR AS V WHERE V.id == 70),
    (SELECT Ex.id FROM EXHIBITION AS Ex WHERE Ex.id == 1),
    '2020-08-12'
);

INSERT INTO VISITS VALUES
(
    (SELECT V.id FROM VISITOR AS V WHERE V.id == 71),
    (SELECT Ex.id FROM EXHIBITION AS Ex WHERE Ex.id == 1),
    '2020-08-12'
);

INSERT INTO VISITS VALUES
(
    (SELECT V.id FROM VISITOR AS V WHERE V.id == 72),
    (SELECT Ex.id FROM EXHIBITION AS Ex WHERE Ex.id == 1),
    '2020-08-12'
);

INSERT INTO VISITS VALUES
(
    (SELECT V.id FROM VISITOR AS V WHERE V.id == 73),
    (SELECT Ex.id FROM EXHIBITION AS Ex WHERE Ex.id == 1),
    '2020-08-12'
);

INSERT INTO VISITS VALUES
(
    (SELECT V.id FROM VISITOR AS V WHERE V.id == 74),
    (SELECT Ex.id FROM EXHIBITION AS Ex WHERE Ex.id == 1),
    '2020-08-12'
);

INSERT INTO VISITS VALUES
(
    (SELECT V.id FROM VISITOR AS V WHERE V.id == 31),
    (SELECT Ex.id FROM EXHIBITION AS Ex WHERE Ex.id == 2),
    '2020-09-19'
);

INSERT INTO VISITS VALUES
(
    (SELECT V.id FROM VISITOR AS V WHERE V.id == 32),
    (SELECT Ex.id FROM EXHIBITION AS Ex WHERE Ex.id == 2),
    '2020-09-19'
);

INSERT INTO VISITS VALUES
(
    (SELECT V.id FROM VISITOR AS V WHERE V.id == 33),
    (SELECT Ex.id FROM EXHIBITION AS Ex WHERE Ex.id == 2),
    '2020-09-19'
);

INSERT INTO VISITS VALUES
(
    (SELECT V.id FROM VISITOR AS V WHERE V.id == 34),
    (SELECT Ex.id FROM EXHIBITION AS Ex WHERE Ex.id == 2),
    '2020-09-19'
);

INSERT INTO VISITS VALUES
(
    (SELECT V.id FROM VISITOR AS V WHERE V.id == 35),
    (SELECT Ex.id FROM EXHIBITION AS Ex WHERE Ex.id == 2),
    '2020-09-19'
);

INSERT INTO VISITS VALUES
(
    (SELECT V.id FROM VISITOR AS V WHERE V.id == 36),
    (SELECT Ex.id FROM EXHIBITION AS Ex WHERE Ex.id == 2),
    '2020-09-19'
);

INSERT INTO VISITS VALUES
(
    (SELECT V.id FROM VISITOR AS V WHERE V.id == 37),
    (SELECT Ex.id FROM EXHIBITION AS Ex WHERE Ex.id == 2),
    '2020-10-12'
);

INSERT INTO VISITS VALUES
(
    (SELECT V.id FROM VISITOR AS V WHERE V.id == 38),
    (SELECT Ex.id FROM EXHIBITION AS Ex WHERE Ex.id == 2),
    '2020-10-12'
);

INSERT INTO VISITS VALUES
(
    (SELECT V.id FROM VISITOR AS V WHERE V.id == 39),
    (SELECT Ex.id FROM EXHIBITION AS Ex WHERE Ex.id == 2),
    '2020-10-12'
);

INSERT INTO VISITS VALUES
(
    (SELECT V.id FROM VISITOR AS V WHERE V.id == 40),
    (SELECT Ex.id FROM EXHIBITION AS Ex WHERE Ex.id == 2),
    '2020-10-12'
);

INSERT INTO VISITS VALUES
(
    (SELECT V.id FROM VISITOR AS V WHERE V.id == 41),
    (SELECT Ex.id FROM EXHIBITION AS Ex WHERE Ex.id == 2),
    '2020-10-12'
);

INSERT INTO VISITS VALUES
(
    (SELECT V.id FROM VISITOR AS V WHERE V.id == 42),
    (SELECT Ex.id FROM EXHIBITION AS Ex WHERE Ex.id == 2),
    '2020-10-12'
);

INSERT INTO VISITS VALUES
(
    (SELECT V.id FROM VISITOR AS V WHERE V.id == 43),
    (SELECT Ex.id FROM EXHIBITION AS Ex WHERE Ex.id == 2),
    '2020-10-12'
);

INSERT INTO VISITS VALUES
(
    (SELECT V.id FROM VISITOR AS V WHERE V.id == 44),
    (SELECT Ex.id FROM EXHIBITION AS Ex WHERE Ex.id == 2),
    '2020-11-25'
);

INSERT INTO VISITS VALUES
(
    (SELECT V.id FROM VISITOR AS V WHERE V.id == 45),
    (SELECT Ex.id FROM EXHIBITION AS Ex WHERE Ex.id == 2),
    '2020-11-25'
);

INSERT INTO VISITS VALUES
(
    (SELECT V.id FROM VISITOR AS V WHERE V.id == 46),
    (SELECT Ex.id FROM EXHIBITION AS Ex WHERE Ex.id == 2),
    '2020-11-25'
);

INSERT INTO VISITS VALUES
(
    (SELECT V.id FROM VISITOR AS V WHERE V.id == 47),
    (SELECT Ex.id FROM EXHIBITION AS Ex WHERE Ex.id == 2),
    '2020-11-25'
);

INSERT INTO VISITS VALUES
(
    (SELECT V.id FROM VISITOR AS V WHERE V.id == 48),
    (SELECT Ex.id FROM EXHIBITION AS Ex WHERE Ex.id == 2),
    '2020-11-25'
);

INSERT INTO VISITS VALUES
(
    (SELECT V.id FROM VISITOR AS V WHERE V.id == 49),
    (SELECT Ex.id FROM EXHIBITION AS Ex WHERE Ex.id == 2),
    '2020-12-29'
);

INSERT INTO VISITS VALUES
(
    (SELECT V.id FROM VISITOR AS V WHERE V.id == 1),
    (SELECT Ex.id FROM EXHIBITION AS Ex WHERE Ex.id == 2),
    '2020-12-29'
);

INSERT INTO VISITS VALUES
(
    (SELECT V.id FROM VISITOR AS V WHERE V.id == 2),
    (SELECT Ex.id FROM EXHIBITION AS Ex WHERE Ex.id == 2),
    '2020-12-29'
);

INSERT INTO VISITS VALUES
(
    (SELECT V.id FROM VISITOR AS V WHERE V.id == 50),
    (SELECT Ex.id FROM EXHIBITION AS Ex WHERE Ex.id == 2),
    '2020-12-29'
);

INSERT INTO VISITS VALUES
(
    (SELECT V.id FROM VISITOR AS V WHERE V.id == 51),
    (SELECT Ex.id FROM EXHIBITION AS Ex WHERE Ex.id == 2),
    '2020-12-29'
);

INSERT INTO VISITS VALUES
(
    (SELECT V.id FROM VISITOR AS V WHERE V.id == 52),
    (SELECT Ex.id FROM EXHIBITION AS Ex WHERE Ex.id == 2),
    '2020-12-29'
);

INSERT INTO VISITS VALUES
(
    (SELECT V.id FROM VISITOR AS V WHERE V.id == 53),
    (SELECT Ex.id FROM EXHIBITION AS Ex WHERE Ex.id == 2),
    '2020-12-29'
);

INSERT INTO VISITS VALUES
(
    (SELECT V.id FROM VISITOR AS V WHERE V.id == 8),
    (SELECT Ex.id FROM EXHIBITION AS Ex WHERE Ex.id == 2),
    '2020-12-29'
);

INSERT INTO VISITS VALUES
(
    (SELECT V.id FROM VISITOR AS V WHERE V.id == 92),
    (SELECT Ex.id FROM EXHIBITION AS Ex WHERE Ex.id == 2),
    '2020-12-29'
);

INSERT INTO VISITS VALUES
(
    (SELECT V.id FROM VISITOR AS V WHERE V.id == 3),
    (SELECT Ex.id FROM EXHIBITION AS Ex WHERE Ex.id == 2),
    '2020-12-29'
);

INSERT INTO VISITS VALUES
(
    (SELECT V.id FROM VISITOR AS V WHERE V.id == 4),
    (SELECT Ex.id FROM EXHIBITION AS Ex WHERE Ex.id == 2),
    '2020-12-29'
);

INSERT INTO VISITS VALUES
(
    (SELECT V.id FROM VISITOR AS V WHERE V.id == 5),
    (SELECT Ex.id FROM EXHIBITION AS Ex WHERE Ex.id == 2),
    '2020-12-29'
);

INSERT INTO VISITS VALUES
(
    (SELECT V.id FROM VISITOR AS V WHERE V.id == 6),
    (SELECT Ex.id FROM EXHIBITION AS Ex WHERE Ex.id == 2),
    '2020-12-29'
);

INSERT INTO VISITS VALUES
(
    (SELECT V.id FROM VISITOR AS V WHERE V.id == 54),
    (SELECT Ex.id FROM EXHIBITION AS Ex WHERE Ex.id == 2),
    '2021-01-14'
);

INSERT INTO VISITS VALUES
(
    (SELECT V.id FROM VISITOR AS V WHERE V.id == 55),
    (SELECT Ex.id FROM EXHIBITION AS Ex WHERE Ex.id == 2),
    '2021-01-14'
);

INSERT INTO VISITS VALUES
(
    (SELECT V.id FROM VISITOR AS V WHERE V.id == 56),
    (SELECT Ex.id FROM EXHIBITION AS Ex WHERE Ex.id == 2),
    '2021-01-14'
);

INSERT INTO VISITS VALUES
(
    (SELECT V.id FROM VISITOR AS V WHERE V.id == 57),
    (SELECT Ex.id FROM EXHIBITION AS Ex WHERE Ex.id == 2),
    '2021-01-14'
);

INSERT INTO VISITS VALUES
(
    (SELECT V.id FROM VISITOR AS V WHERE V.id == 58),
    (SELECT Ex.id FROM EXHIBITION AS Ex WHERE Ex.id == 2),
    '2021-01-14'
);

INSERT INTO VISITS VALUES
(
    (SELECT V.id FROM VISITOR AS V WHERE V.id == 26),
    (SELECT Ex.id FROM EXHIBITION AS Ex WHERE Ex.id == 2),
    '2021-01-14'
);

INSERT INTO VISITS VALUES
(
    (SELECT V.id FROM VISITOR AS V WHERE V.id == 1),
    (SELECT Ex.id FROM EXHIBITION AS Ex WHERE Ex.id == 2),
    '2021-01-14'
);

INSERT INTO VISITS VALUES
(
    (SELECT V.id FROM VISITOR AS V WHERE V.id == 9),
    (SELECT Ex.id FROM EXHIBITION AS Ex WHERE Ex.id == 2),
    '2021-01-14'
);

INSERT INTO VISITS VALUES
(
    (SELECT V.id FROM VISITOR AS V WHERE V.id == 4),
    (SELECT Ex.id FROM EXHIBITION AS Ex WHERE Ex.id == 2),
    '2021-01-14'
);

INSERT INTO VISITS VALUES
(
    (SELECT V.id FROM VISITOR AS V WHERE V.id == 91),
    (SELECT Ex.id FROM EXHIBITION AS Ex WHERE Ex.id == 2),
    '2021-01-14'
);

INSERT INTO VISITS VALUES
(
    (SELECT V.id FROM VISITOR AS V WHERE V.id == 10),
    (SELECT Ex.id FROM EXHIBITION AS Ex WHERE Ex.id == 2),
    '2021-01-14'
);

INSERT INTO VISITS VALUES
(
    (SELECT V.id FROM VISITOR AS V WHERE V.id == 11),
    (SELECT Ex.id FROM EXHIBITION AS Ex WHERE Ex.id == 2),
    '2021-01-14'
);
--Αλλαγή εκεθσης
INSERT INTO VISITS VALUES
(
    (SELECT V.id FROM VISITOR AS V WHERE V.id == 60),
    (SELECT Ex.id FROM EXHIBITION AS Ex WHERE Ex.id == 3),
    '2021-02-26'
);

INSERT INTO VISITS VALUES
(   
    (SELECT V.id FROM VISITOR AS V WHERE V.id == 61),
    (SELECT Ex.id FROM EXHIBITION AS Ex WHERE Ex.id == 3),
    '2021-02-26'
);

INSERT INTO VISITS VALUES
(
    (SELECT V.id FROM VISITOR AS V WHERE V.id == 62),
    (SELECT Ex.id FROM EXHIBITION AS Ex WHERE Ex.id == 3),
    '2021-02-26'
);

INSERT INTO VISITS VALUES
(
    (SELECT V.id FROM VISITOR AS V WHERE V.id == 63),
    (SELECT Ex.id FROM EXHIBITION AS Ex WHERE Ex.id == 3),
    '2021-02-26'
);

INSERT INTO VISITS VALUES
(
    (SELECT V.id FROM VISITOR AS V WHERE V.id == 64),
    (SELECT Ex.id FROM EXHIBITION AS Ex WHERE Ex.id == 3),
    '2021-02-26'
);

INSERT INTO VISITS VALUES
(
    (SELECT V.id FROM VISITOR AS V WHERE V.id == 65),
    (SELECT Ex.id FROM EXHIBITION AS Ex WHERE Ex.id == 3),
    '2021-02-26'
);

INSERT INTO VISITS VALUES
(
    (SELECT V.id FROM VISITOR AS V WHERE V.id == 66),
    (SELECT Ex.id FROM EXHIBITION AS Ex WHERE Ex.id == 3),
    '2021-02-26'
);

INSERT INTO VISITS VALUES
(
    (SELECT V.id FROM VISITOR AS V WHERE V.id == 67),
    (SELECT Ex.id FROM EXHIBITION AS Ex WHERE Ex.id == 3),
    '2021-02-26'
);

INSERT INTO VISITS VALUES
(
    (SELECT V.id FROM VISITOR AS V WHERE V.id == 22),
    (SELECT Ex.id FROM EXHIBITION AS Ex WHERE Ex.id == 3),
    '2021-02-26'
);

INSERT INTO VISITS VALUES
(
    (SELECT V.id FROM VISITOR AS V WHERE V.id == 23),
    (SELECT Ex.id FROM EXHIBITION AS Ex WHERE Ex.id == 3),
    '2021-02-26'
);

INSERT INTO VISITS VALUES
(
    (SELECT V.id FROM VISITOR AS V WHERE V.id == 24),
    (SELECT Ex.id FROM EXHIBITION AS Ex WHERE Ex.id == 3),
    '2021-02-26'
);

INSERT INTO VISITS VALUES
(
    (SELECT V.id FROM VISITOR AS V WHERE V.id == 32),
    (SELECT Ex.id FROM EXHIBITION AS Ex WHERE Ex.id == 3),
    '2021-02-26'
);

INSERT INTO VISITS VALUES
(
    (SELECT V.id FROM VISITOR AS V WHERE V.id == 35),
    (SELECT Ex.id FROM EXHIBITION AS Ex WHERE Ex.id == 3),
    '2021-02-26'
);

INSERT INTO VISITS VALUES
(
    (SELECT V.id FROM VISITOR AS V WHERE V.id == 68),
    (SELECT Ex.id FROM EXHIBITION AS Ex WHERE Ex.id == 3),
    '2021-03-13'
);

INSERT INTO VISITS VALUES
(
    (SELECT V.id FROM VISITOR AS V WHERE V.id == 69),
    (SELECT Ex.id FROM EXHIBITION AS Ex WHERE Ex.id == 3),
    '2021-03-13'
);

INSERT INTO VISITS VALUES
(
    (SELECT V.id FROM VISITOR AS V WHERE V.id == 70),
    (SELECT Ex.id FROM EXHIBITION AS Ex WHERE Ex.id == 3),
    '2021-03-13'
);

INSERT INTO VISITS VALUES
(
    (SELECT V.id FROM VISITOR AS V WHERE V.id == 71),
    (SELECT Ex.id FROM EXHIBITION AS Ex WHERE Ex.id == 3),
    '2021-03-13'
);

INSERT INTO VISITS VALUES
(
    (SELECT V.id FROM VISITOR AS V WHERE V.id == 72),
    (SELECT Ex.id FROM EXHIBITION AS Ex WHERE Ex.id == 3),
    '2021-03-13'
);

INSERT INTO VISITS VALUES
(
    (SELECT V.id FROM VISITOR AS V WHERE V.id == 73),
    (SELECT Ex.id FROM EXHIBITION AS Ex WHERE Ex.id == 3),
    '2021-03-13'
);

INSERT INTO VISITS VALUES
(
    (SELECT V.id FROM VISITOR AS V WHERE V.id == 74),
    (SELECT Ex.id FROM EXHIBITION AS Ex WHERE Ex.id == 3),
    '2021-03-13'
);

INSERT INTO VISITS VALUES
(
    (SELECT V.id FROM VISITOR AS V WHERE V.id == 19),
    (SELECT Ex.id FROM EXHIBITION AS Ex WHERE Ex.id == 3),
    '2021-03-13'
);

INSERT INTO VISITS VALUES
(
    (SELECT V.id FROM VISITOR AS V WHERE V.id == 62),
    (SELECT Ex.id FROM EXHIBITION AS Ex WHERE Ex.id == 3),
    '2021-03-13'
);

INSERT INTO VISITS VALUES
(
    (SELECT V.id FROM VISITOR AS V WHERE V.id == 46),
    (SELECT Ex.id FROM EXHIBITION AS Ex WHERE Ex.id == 3),
    '2021-03-13'
);

INSERT INTO VISITS VALUES
(
    (SELECT V.id FROM VISITOR AS V WHERE V.id == 47),
    (SELECT Ex.id FROM EXHIBITION AS Ex WHERE Ex.id == 3),
    '2021-03-13'
);

INSERT INTO VISITS VALUES
(
    (SELECT V.id FROM VISITOR AS V WHERE V.id == 48),
    (SELECT Ex.id FROM EXHIBITION AS Ex WHERE Ex.id == 3),
    '2021-03-13'
);

INSERT INTO VISITS VALUES
(
    (SELECT V.id FROM VISITOR AS V WHERE V.id == 50),
    (SELECT Ex.id FROM EXHIBITION AS Ex WHERE Ex.id == 3),
    '2021-03-13'
);

INSERT INTO VISITS VALUES
(
    (SELECT V.id FROM VISITOR AS V WHERE V.id == 75),
    (SELECT Ex.id FROM EXHIBITION AS Ex WHERE Ex.id == 3),
    '2021-04-06'
);

INSERT INTO VISITS VALUES
(
    (SELECT V.id FROM VISITOR AS V WHERE V.id == 76),
    (SELECT Ex.id FROM EXHIBITION AS Ex WHERE Ex.id == 3),
    '2021-04-06'
);

INSERT INTO VISITS VALUES
(
    (SELECT V.id FROM VISITOR AS V WHERE V.id == 77),
    (SELECT Ex.id FROM EXHIBITION AS Ex WHERE Ex.id == 3),
    '2021-04-06'
);

INSERT INTO VISITS VALUES
(
    (SELECT V.id FROM VISITOR AS V WHERE V.id == 78),
    (SELECT Ex.id FROM EXHIBITION AS Ex WHERE Ex.id == 3),
    '2021-04-06'
);

INSERT INTO VISITS VALUES
(
    (SELECT V.id FROM VISITOR AS V WHERE V.id == 79),
    (SELECT Ex.id FROM EXHIBITION AS Ex WHERE Ex.id == 3),
    '2021-04-06'
);

INSERT INTO VISITS VALUES
(
    (SELECT V.id FROM VISITOR AS V WHERE V.id == 80),
    (SELECT Ex.id FROM EXHIBITION AS Ex WHERE Ex.id == 3),
    '2021-04-06'
);

INSERT INTO VISITS VALUES
(
    (SELECT V.id FROM VISITOR AS V WHERE V.id == 81),
    (SELECT Ex.id FROM EXHIBITION AS Ex WHERE Ex.id == 3),
    '2021-05-22'
);

INSERT INTO VISITS VALUES
(
    (SELECT V.id FROM VISITOR AS V WHERE V.id == 82),
    (SELECT Ex.id FROM EXHIBITION AS Ex WHERE Ex.id == 3),
    '2021-05-22'
);

INSERT INTO VISITS VALUES
(
    (SELECT V.id FROM VISITOR AS V WHERE V.id == 20),
    (SELECT Ex.id FROM EXHIBITION AS Ex WHERE Ex.id == 3),
    '2021-05-22'
);

INSERT INTO VISITS VALUES
(
    (SELECT V.id FROM VISITOR AS V WHERE V.id == 83),
    (SELECT Ex.id FROM EXHIBITION AS Ex WHERE Ex.id == 3),
    '2021-05-22'
);

INSERT INTO VISITS VALUES
(
    (SELECT V.id FROM VISITOR AS V WHERE V.id == 84),
    (SELECT Ex.id FROM EXHIBITION AS Ex WHERE Ex.id == 3),
    '2021-05-22'
);

INSERT INTO VISITS VALUES
(
    (SELECT V.id FROM VISITOR AS V WHERE V.id == 85),
    (SELECT Ex.id FROM EXHIBITION AS Ex WHERE Ex.id == 3),
    '2021-06-08'
);

INSERT INTO VISITS VALUES
(
    (SELECT V.id FROM VISITOR AS V WHERE V.id == 86),
    (SELECT Ex.id FROM EXHIBITION AS Ex WHERE Ex.id == 3),
    '2021-06-08'
);

INSERT INTO VISITS VALUES
(
    (SELECT V.id FROM VISITOR AS V WHERE V.id == 87),
    (SELECT Ex.id FROM EXHIBITION AS Ex WHERE Ex.id == 3),
    '2021-06-08'
);

INSERT INTO VISITS VALUES
(
    (SELECT V.id FROM VISITOR AS V WHERE V.id == 88),
    (SELECT Ex.id FROM EXHIBITION AS Ex WHERE Ex.id == 3),
    '2021-06-08'
);

INSERT INTO VISITS VALUES
(
    (SELECT V.id FROM VISITOR AS V WHERE V.id == 89),
    (SELECT Ex.id FROM EXHIBITION AS Ex WHERE Ex.id == 3),
    '2021-06-08'
);

INSERT INTO VISITS VALUES
(
    (SELECT V.id FROM VISITOR AS V WHERE V.id == 90),
    (SELECT Ex.id FROM EXHIBITION AS Ex WHERE Ex.id == 3),
    '2021-06-08'
);

INSERT INTO VISITS VALUES
(
    (SELECT V.id FROM VISITOR AS V WHERE V.id == 91),
    (SELECT Ex.id FROM EXHIBITION AS Ex WHERE Ex.id == 3),
    '2021-06-08'
);

INSERT INTO VISITS VALUES
(
    (SELECT V.id FROM VISITOR AS V WHERE V.id == 92),
    (SELECT Ex.id FROM EXHIBITION AS Ex WHERE Ex.id == 3),
    '2021-06-24'
);

INSERT INTO VISITS VALUES
(
    (SELECT V.id FROM VISITOR AS V WHERE V.id == 93),
    (SELECT Ex.id FROM EXHIBITION AS Ex WHERE Ex.id == 3),
    '2021-06-24'
);

INSERT INTO VISITS VALUES
(
    (SELECT V.id FROM VISITOR AS V WHERE V.id == 94),
    (SELECT Ex.id FROM EXHIBITION AS Ex WHERE Ex.id == 3),
    '2021-06-24'
);

INSERT INTO VISITS VALUES
(
    (SELECT V.id FROM VISITOR AS V WHERE V.id == 95),
    (SELECT Ex.id FROM EXHIBITION AS Ex WHERE Ex.id == 3),
    '2021-07-15'
);

INSERT INTO VISITS VALUES
(
    (SELECT V.id FROM VISITOR AS V WHERE V.id == 96),
    (SELECT Ex.id FROM EXHIBITION AS Ex WHERE Ex.id == 3),
    '2021-07-15'
);

INSERT INTO VISITS VALUES
(
    (SELECT V.id FROM VISITOR AS V WHERE V.id == 97),
    (SELECT Ex.id FROM EXHIBITION AS Ex WHERE Ex.id == 3),
    '2021-07-15'
);

INSERT INTO VISITS VALUES
(
    (SELECT V.id FROM VISITOR AS V WHERE V.id == 98),
    (SELECT Ex.id FROM EXHIBITION AS Ex WHERE Ex.id == 3),
    '2021-07-15'
);

INSERT INTO VISITS VALUES
(
    (SELECT V.id FROM VISITOR AS V WHERE V.id == 99),
    (SELECT Ex.id FROM EXHIBITION AS Ex WHERE Ex.id == 3),
    '2021-07-15'
);

INSERT INTO VISITS VALUES
(
    (SELECT V.id FROM VISITOR AS V WHERE V.id == 100),
    (SELECT Ex.id FROM EXHIBITION AS Ex WHERE Ex.id == 3),
    '2021-07-15'
);
